# /lib/systemd/system/@(Package).service
#
# This is a systemd service unit file generated by bloom from the following
# template:
#
# ros-bloom-debhelper/src/my_project/debian/service.em

[Unit]
Description="@(Description)"
After=network.target

[Service]
ExecStart=/bin/sh -c '. @(InstallationPrefix)/setup.sh && @(InstallationPrefix)/bin/@(Name.replace('_','-'))

[Install]
WantedBy=default.target
